poppler: Autospec creation for update from version 22.01.0 to version 22.04.0
ANaumann85 (1):
      Fix underline sometimes being drawn only partially

Albert Astals Cid (117):
      qt: Allow passing the document password when signing
      Make DefaultAppearance::toAppearanceString return a std::string
      Update (C) of commit-1
      Add (C)
      Update (C)
      SignatureHandler: Access CERT_NameTemplate in a Windows/Android compatible way
      Make GDir::getNextEntry return a unique pointer
      Use GDir in getDefaultFirefoxCertDB_Linux
      Fix including gdir.h in Windows
      FindNSS3: Improve documentation and remove "wrong" MSVC check
      SignatureHandler: Fix crashes on Windows
      pdfsig: Fix compile with MSVC
      Fix glib compilation on MSVC
      Revert e2ec957c0174a36396c3e8c194f44a1f300a950f
      Add a way to detect unsigned FormFieldSignature
      [qt] Add FormFieldSignature::sign
      Update (C)
      Fix leak introduced in 953c9c762f346236d856327833f3a550b993138a
      AnnotAppearanceCharacs: Also initialize position when !dict
      Use default X509CertificateInfo::EntityInfo operator=
      qt5: cleanup todos, we already require that qt version since a while
      Windows: Fix path where to look for firefox NSS DB
      Popppler 22.02.0
      Improve PDFDoc::getSignatureFields
      Fix getting the home dir in Windows
      Be more resiliant against env variables not being set
      Windows: Better way to access Mozilla appdata
      qt: Change typedefs to using
      Remove PDFDoc::init
      Remove ViewerPreferences::init
      PDFDoc: Remove useless checks in destructor
      Make Catalog::embeddedFile return an unique_ptr
      Error: Save newing/deleting a GooString
      Make utf8ToUtf16WithBom return a unique_ptr
      Make UnicodeMap::parse return an unique_ptr
      Update (C) of previous commits
      Use the "superior" C++17 std::scoped_lock
      Remove LinkDest::copy
      HtmlOutputDev: Remove useless GooString
      Make Movie::copy return an unique_ptr
      Change PDFDoc::save from pointer to reference
      Make PDFDoc constructor take the filename as unique_ptr
      pdfimages: Fix the wrong Stream being passed for drawMaskedImage
      PDFDoc: Make passwords std::optional instead of pointers
      CMap: Turn manual refcounting into using shared_ptr
      We don't use pthreads anymore, cleanup cmake stuff around it
      Update (C) of last commit
      Update (C)
      qt: Remove unneeded unique_ptr constructor
      qt: Store QFont as an optional
      poppler 22.03.0
      Annot::setContents: Take a unique_ptr
      AnnotMarkup::setLabel: Take a unique_ptr
      qt: Annotations, don't change the text color when changing the font
      qt: Add a few "don't do anything if you're setting the same value we already have"
      qt: Handle SaveAs named action
      qt: Add qWarnings for non supported scenarios
      FoFiTrueType: Parse CFF2 fonts too
      Update (C)
      Move makeFileDescriptorCloexec inside the #if its used in
      Annot::getRect: Return a const & instead of a pointer
      GooString: Add lowercase helpers for std::string
      glib: Fix returning c_str() of temporal strings
      If you want to build the cpp frontend iconv is required
      CI: Install libtiff-dev for ubuntu
      Fix easy warning when building on mingw
      Require the min freetype of our minimum linux base
      Update (C) of previous commit
      Update (C) of previous commit
      Make GooFile::open return an unique_ptr
      Add readability-braces-around-statements
      Update .git-blame-ignore-revs
      Update (C) from last commit
      Update (C)
      cpp: Remove bit size qualifier from format variable
      cpp: Remove no longer needed const_cast
      Hints::readTables: bail out if we run out of file when reading
      Update (C)
      Fix crash caused by efe7d77838896ddcefb838f382628ae31be54d99
      Limit complaining about missing ID for encrypted files
      Form: Don't store stuff we don't use
      Move AnnotAppearanceBuilder::writeString to std::string
      Make cidToGIDLen unsigned
      CI: Use the qt6 provided by debian
      Update (C)
      Write unicode strings using PDF hexadecimal strings
      Trigger xref rebuild properly
      regtest: Add a command to download files
      AnnotAppearanceBuilder::drawText: Merge 4 bools into a flags variable
      Unify 2 enums and a set of defines into an enum
      Rename comb to combMaxLen
      Annot::drawText: Move combMaxLen to the end since it's only used once
      More variable improvements in AnnotAppearanceBuilder::drawText
      AnnotAppearanceBuilder::drawText: Use FormFieldText::tokenizeDA
      Remove checks for tfPos being >= 0
      Simplify code by ensuring there's always Tm in daToks
      We don't need to force STATIC on MSVC anymore
      Fix memory leak
      Remove unused function
      CI: switch to debian testing while they fix the python migration mess
      One/Two more GooString to std::string
      GooString: Introduce string_view ends/startsWith functions
      CI: We can go back to debian:unstable now
      Update (C)
      Port PSOutputDev::filterPSName to std::string
      Rename variable, it's actually the number of cells
      Make GooString::format[v] return an unique_ptr
      Fix regression caused by a6b2442e37cc00534bcdca7c83366a0fa0501157
      Move Catalog baseURI to optional string
      Convert CharCodeToUnicode tag to optional string
      Remove the url from the CachedFileLoader::init function
      Change GfxFont name into an optional std::string
      Fix crash introduced in dbbaa1651dc168f71054e3dd9ef91e33c960bfb7
      (C) of last commits
      CI: make the libcpp build use C++23
      Fix regression caused by d72c22caf28cbe8cf1e268f8ff741d7e1330df63
      Poppler 22.04.0

Christian Persch (1):
      glib: Fix mem leak in poppler_document_new_from_fd

Even Rouault (2):
      GooString: only export non-inline methods, not the whole class
      GlobalParams::setupBaseFonts(): fix memory leaks related to GooString

Fabrice Fontaine (1):
      glib/CMakeLists.txt: allow the user to configure INTROSPECTION_COMPILER_ARGS

Felix Jung (1):
      qt: Pass leftFontSize down to `PDFDoc::signsign` so it's actually used

Kai Pastor (7):
      Use output variable from CMake find modules
      Don't use CURL_INCLUDE_DIRS with CURL::libcurl
      Concentrate LCMS CMake setup
      Concentrate OpenJPEG CMake setup
      Concentrate JPEG CMake setup
      Concentrate Fontconfig CMake setup
      Use Freetype::Freetype

Marek Kasik (2):
      PDFDoc: Count only signature fields in getNumSignatureFields
      glib: New method for getting all signature fields

Martin (2):
      AnnotAppearanceBuilder: Also use the image when there is left signature text
      [qt] Add PDFConverter::NewSignatureData::imagePath

Nelson Benítez León (1):
      glib: try with utf8 password if latin1 fails

Oliver Sander (20):
      Make a few GooString* arguments const
      Remove spurious double include
      Store 'path' as std::string in GfxFontLoc
      Allocate GfxFontLoc object on the stack
      Let FoFiTrueType::make and ...::load return std::unique_ptr
      Remove a bit of duplicate code
      Store the strings in FontInfo in std::optional<std::string>
      Import improved line join handling from xpdf 4.02
      Use new/delete for class type3_font_info_t
      Let type3_font_info_t have a constructor that takes all information
      Make method getWMode const
      Store GfxFontDict::fonts in a std::vector
      Replace hand-coded reference counting in GfxFont by std::shared_ptr
      Remove method SplashFontSrc::setFile(const char *file, bool del)
      Remove the deleteSrc variable from SplashFontSrc
      Use std::string for filename in SplashFontSrc
      Rewrite Cairo font caching without hashing the entire font
      Pass around font memory buffers as unsigned char
      Simplify method _ft_new_face_uncached
      Store font data in a std::vector<unsigned char>

Stefan Löffler (1):
      Fix poppler_localdir for relocatable Windows builds

Zachary Travis (2):
      Type 2 cmap
      Add support for format 13 as well

kVdNi (1):
      pdftotext now prints creation and modification date when using htmlmeta param

Release 22.04.0:
        core:
         * Fix underline sometimes being drawn only partially
         * Fix Adobe Reader not reading some of the contents we write correctly
         * Fix code that workarounds some broken-ish files
         * FoFiTrueType: Parse CFF2 fonts too
         * FoFiTrueType: Support cmap types 2 and 13
         * Fix a few small memory leaks
         * code improvements

        qt:
         * Handle SaveAs named action
         * Annotations: don't change the text color when changing the font

        utils:

(NEWS truncated at 15 lines)